export const userApi = {
    routes : {
        login :"admin/login",
        userProfile:"admin/profile",
        refreshToken:"admin/refresh",
        getBanners:"banner/list",
        createBanners:"banner/create",
        deleteBanner:"banner/delete",
        editBanner:"banner/update",
        getCategories:"category/list",
        createCategory:"category/create",
        updateCategory:"category/update",
        deleteCategory:"category/delete",
        getProducts:"product/list",
        createproduct:"product/create",
        updateproduct:"product/update",
        deleteproduct:"product/delete",
        fetchEmployee:"admin/list",
        createEmployee:"admin/create",
        deleteEmployee:"admin/delete",
        updateEmployee:"admin/update",
        fetchUsers:"user/list",
        deleteUsers:"user/delete",
        createUser:"user/create",
        updateUser:"user/update",
        fetchContatc:"contacts/list",
        createContact:"contacts/create",
        updateContact:"contacts/update",
        deleteContact:"contacts/delete",
        fetchSocials:"social_media/list",
        createSocial:"social_media/create",
        updateSocials:"social_media/update",
        deleteSocials:"social_media/delete",
        fetchSetting:"settings/list",
        updateSetting:"settings/update",
        fetchNotification : "notification/list",
        fetchInstallments: "installments/list",
        createInstallment :"installments/create",
        updateInstallment :"installments/update",
        deleteInstallment:"installments/delete",
        createCategoryInstallment :"category/installment/create",
        deleteCategoryInstallment :"category/installment/delete",
        updateCategoryInstallment :"category/installment/update",
    }
}